Dol Library Improvement
terorie/ppc750cl pull request #40
Opened 2022-06-02 01:00 UTC by InusualZ

The first commit I borrowed from your #22 PR, the only thing that I added was proper error handling which you left as to-do.

The second commit, is the main reason of why I did this PR. I wanted to use the full `Dol` lib in [my project](https://github.com/InusualZ/dadosod), but it's lacking that `DolSectionType::Text`. Why you decided against it in the first place?

Also, why is the code that [verify section overlap](https://github.com/terorie/ppc750cl/blob/619c935dc4979ff54abad7ee99412c2e257c03ab/dol/src/lib.rs#L66-L73) commented?

2022-06-02 02:29 UTC, terorie requested changes

2022-06-02 02:29 UTC, terorie commented on dol/src/lib.rs
> +            data.copy_from_slice(&self.memory[offset..offset + data.len()]);
I think we should check for `offset` too, might also be OOB

2022-06-02 02:29 UTC, terorie commented on dol/src/lib.rs
>          let offset = (virtual_addr - self.memory_offset) as usize;
If `virtual_addr` is smaller than `self.memory_offset`, this will panic on debug mode (integer underflow checks), so this also needs a bounds check.

2022-06-02 02:29 UTC, terorie commented on dol/src/lib.rs
> +    OutOfBound(u32)
```suggestion
    OutOfBounds(u32)
```
Maybe let's call the error something more descriptive like `attempted to access {0:08X} past DOL bounds`?

2022-06-04 10:52 UTC, InusualZ commented
Is there anything else blocking this PR?

2022-06-09 00:54 UTC, InusualZ commented
All should be fixed now. (Sorry for the double push)

2022-06-09 05:28 UTC, terorie commented
@InusualZ You can push as many times as you like, no worries. Seems like only one more minor format thing, I'll fix that. Btw, have you seen https://github.com/radare-org/radare2 ? They have a complete Wii disassembler and symbolic execution engine. It has far more features than this project.

2022-06-09 05:30 UTC, merged

2022-06-09 12:24 UTC, InusualZ commented
I knew about redare, but I didn’t know about the Wii disassembler. The only problem that I have with redare is his interface. I don’t quite like that if you want to interact with most of his service it need to be done through a “shell”

2022-06-09 19:20 UTC, terorie commented
@InusualZ The author recently updated the `r2libr` bindings so you can use it as a normal library, albeit using an unsafe C-like interface. I'll keep exploring it and let you know if/when we can retire this ^^